# Generated by Django 6.0.3 on 2026-04-18 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True, verbose_name='immutable name for service purposes')),
                ('label', models.CharField(max_length=256, verbose_name='human readable name')),
                ('type', models.CharField(max_length=30, verbose_name='type of attribute: {text, number, enum, date, boolean}')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeEnumValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('label', models.CharField(max_length=256)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
            ],
        ),
    ]
