# Generated by Django 6.0.3 on 2026-04-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('boolean', 'Boolean'), ('enum', 'Enum'), ('date', 'Date'), ('number', 'Number')], max_length=20, verbose_name='type of attribute: {text, number, enum, date, boolean}'),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['text', 'boolean', 'enum', 'date', 'number'])), name='type_valid'),
        ),
    ]
