# Generated by Django 6.0.3 on 2026-04-18 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=512)),
                ('attributes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
