# Generated by Django 6.0.3 on 2026-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_alter_attribute_type_attribute_type_valid'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='attributes',
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(null=True, to='attribute.attribute'),
        ),
    ]
