# Generated by Django 6.0.3 on 2026-04-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_alter_ad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adattributevalue',
            name='value_bool',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='adattributevalue',
            name='value_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='adattributevalue',
            name='value_number',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='adattributevalue',
            name='value_string',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
