# Generated by Django 6.0.3 on 2026-04-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_alter_adattributevalue_value_bool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='photo',
            field=models.URLField(null=True, verbose_name='photo link'),
        ),
        migrations.AlterField(
            model_name='adattributevalue',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_values', to='ad.ad'),
        ),
    ]
